site_name: Docker & Mkdocs
site_url: "https://box-doc.com"
use_directory_urls: false
nav:
  - Quick start: index.md
  - Introduce: about.md
  - Installation: installation.md
  - Documents:
    - Docker:
      - Command: dockerCmd.md
      - Example: dockerExample.md
    - Mkdocs:
      - Command: mkdocCmd.md
      - Example: mkdocExample.md
  - References: ref.md
theme:
  name: readthedocs
